---
# Remmina
- name: Install Remmina
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  with_items:
    - remmina
    - remmina-plugin-open
    - remmina-plugin-rdesktop
    - remmina-plugin-ultravnc
    - freerdp
  tags: [ 'remmina' ]
