---
- name: Install logid
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: logiops
    state: present
    use: yay
  tags: ['logid']

- name: Copy config
  copy:
    src: files/logid.cfg
    dest: "/etc/logid.cfg"
    owner: root
    group: root
  tags: [ 'logid' ]
