---
- hosts: all
  become: true
  become_method: sudo

  roles:
    - sublime
    - zsh
    - terminator
    - vim
    - docker
    - albert
    - flameshot
    - plasma
    - ssh
    - virtualbox
    - sound

  tasks:
   - name: install apps from aur
     yay:
       name: "{{ item }}"
       user: "{{ user.name }}"
       dir: "/opt/"
     with_items:
       - jetbrains-toolbox
       - teams
       - slack-desktop
       - discord
       - zoom
       - peek
       - mc
       - htop
       - meld
       - remmina
       - remmina-plugin-open
       - remmina-plugin-rdesktop
       - nautilus
       - telegram-desktop
       - nodejs
       - npm
       - code
       - speedcrunch
       - cutecom
       - mongodb-compass
       - obinskit
       - lsof
       - nmap
       - tcpdump
     tags: [ 'aur_apps' ]
