# add fzf

---
- hosts: all
  become: true
  become_method: sudo
  roles:
    - aur_apps
    - sublime
    - zsh
    - terminator
    - vim
    - docker
    - albert
    - flameshot
    - plasma
    - ssh
    - kubernetes
    - tmuxinator
    - remmina
    - logid
    - firewall
    - bluetooth
# sudo ln -sv /usr/bin/ksshaskpass /usr/lib/ssh/ssh-askpass
