---
- hosts: all
  become: true
  become_method: sudo
  roles:
    - aur_apps
    - sublime
    - zsh
    - terminator
    - vim
    - docker
    - albert
    - flameshot
    - plasma
    - ssh
    - virtualbox
    - sound
    - kubernetes
    - tmuxinator
    - remmina
    - logid



# sudo ln -sv /usr/bin/ksshaskpass /usr/lib/ssh/ssh-askpass
