---
- name: install apps from aur
  yay:
    name: "{{ item }}"
    user: "{{ user.name }}"
    dir: "/opt/"
  with_items:
    - terminator
    - jetbrains-toolbox
    - teamviewer
    - filezilla
    - discord
    - peek
    - mc
    - htop
    - meld
    - nautilus
    - telegram-desktop
    - nodejs
    - npm
    - code
    - code-marketplace
    - speedcrunch
    - cutecom
    - lsof
    - nmap
    - tcpdump
    - gimp
    - calibre
    - ripgrep
    - tokei
    - postman-bin
    - cups
    - ghostscript
    - subversion
    - chromium
    - wine
    - noto-fonts-emoji
    - vlc
    - libreoffice-still
    - sane
    - sane-airscan
    - obsidian
    - spotify
    - kooha
    - xdg-desktop-portal
    - xdg-desktop-portal-kde
    - strongswan
    - networkmanager-strongswan

  tags: [ 'aur_apps' ]
