---
- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel
  tags: [ 'aur_apps' ]

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'
  tags: [ 'aur_apps' ]

- name: install apps from aur
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  with_items:
    - terminator
    - jetbrains-toolbox
    - filezilla
    - discord
    - mc
    - htop
    - meld
    - nautilus
    - telegram-desktop
    - nodejs
    - npm
    - code
    - code-marketplace
    - speedcrunch
    - cutecom
    - lsof
    - nmap
    - tcpdump
    - gimp
    - calibre
    - ripgrep
    - tokei
    - postman-bin
    - cups
    - ghostscript
    - subversion
    - chromium
    - noto-fonts-emoji
    - vlc
    - sane
    - sane-airscan
    - obsidian
    - spotify
    - xdg-desktop-portal
    - xdg-desktop-portal-kde
    - strongswan
    - networkmanager-strongswan
    - ntfs-3g
    - fzf
    - go-task-git
    - libreoffice-still
    - libreoffice-still-de
    - gvfs-smb
    - restic
  tags: [ 'aur_apps' ]
