---
- name: install apps from aur
  yay:
    name: "{{ item }}"
    user: "{{ user.name }}"
    dir: "/opt/"
  with_items:
    - netctl
  notify:
    - stop NetworkManager
  tags: ["netctl"]

- name: Copy config
  copy:
    # To get valid Key use "wpa_passphrase MikroTik_lBeJIuk_5 raw_wifi_key"
    src: files/wpa_mikrotik_5
    dest: "/etc/netctl/wpa_mikrotik_5"
  tags: ["netctl"]
  notify:
    - start netctl
    - enable netctl
