---
- name: install apps from aur
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  with_items:
    - input-wacom-dkms
    - kcm-wacomtablet
    - xf86-input-wacom
  tags: [ 'wacom' ]