---
- name: install openssh
  package:
    name: openssh
    state: present
  tags: [ 'ssh' ]

- name: ensure ~/.config/systemd/user is dir
  file:
    path: "/home/{{ user.name }}/.config/systemd/user"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ 'ssh' ]

- name: generate ssh-agent.service
  template:
    src: ssh-agent.service.j2
    dest: "/home/{{ user.name }}/.config/systemd/user/ssh-agent.service"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  tags: [ 'ssh' ]
  notify:
    - restart ssh-agent
