---
- name: install zsh and dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - zsh
  tags: [ 'zsh' ]

- name: use oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "/home/{{ ansible_user }}/.oh-my-zsh"
    version: master
  tags: [ 'zsh' ]

- name: clone theme
  git:
    repo: "https://github.com/bhilburn/powerlevel9k.git"
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/themes/powerlevel9k"
    version: master
  tags: [ 'zsh' ]

- name: Copy config
  copy:
    src: files/.zshrc
    dest: "/home/{{ user.name }}/.zshrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: change shell from bash to zsh
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  tags: [ 'zsh' ]
