---
- name: enable logid daemon
  systemd:
    name: logid.service
    daemon_reload: yes
    enabled: yes
  tags: [ "logid" ]

- name: restart logid daemon
  systemd:
    name: logid.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  tags: [ "logid" ]
