---
- name: Install flameshot
  package:
    name: flameshot
    state: present
  tags: [ "flameshot" ]

- name: create ~/.config/flameshot diretory
  file:
    path: "/home/{{ user.name }}/.config/flameshot"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ "flameshot" ]

- name: Generate config
  template:
    src: flameshot.ini.j2
    dest: "/home/{{ user.name }}/.config/flameshot/flameshot.ini.j2"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
  tags: [ "flameshot" ]
