---
- name: Install kubernetes
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  with_items:
    - kubectl
    - kubelet-bin
    - kubeadm-bin
    - cni-plugins
    - ethtool
    - conntrack-tools
  tags: ['kubernetes']

- name: restart kubelet
  become: true
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  tags: [ 'kubernetes' ]
