---
- name: Install kubernetes
  yay:
    name: " {{ item }}"
    user: "{{ user.name }}"
    dir: "/opt/"
  with_items:
    - kubectl
    - kubelet-bin
    - kubeadm-bin
    - cni-plugins
    - ebtables
    - ethtool
    - conntrack-tools
  tags: ['kubernetes']

- name: restart kubelet
  become: true
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  tags: [ 'kubernetes' ]
