---
- name: restart ssh-agent
  become: false
  systemd:
    name: ssh-agent
    daemon_reload: yes
    state: restarted
    enabled: yes
    scope: "user"
  tags: ['ssh']

- name: restart sshd
  become: true
  systemd:
    name: sshd
    daemon_reload: yes
    state: restarted
    enabled: yes
  tags: ['ssh']
