---
- name: Install additionals for virtualbox
  yay:
    name: "{{ item }} "
    user: "{{ user.name }}"
    dir: "/opt/"
  with_items:
    - virtualbox-ext-oracle
    - virtualbox-host-dkms
    - linux510-headers
  tags: ['virtualbox']

- name: install virtualbox
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - net-tools
    - virtualbox-guest-iso
    - virtualbox
  notify:
   - vboxreload
   - modprobe
  tags: [ 'virtualbox' ]
