---
- name: Install vim
  package:
    name: vim
    state: present
  tags: [ "vim" ]

- name: create ~/.vim diretory
  file:
    path: "/home/{{ user.name }}/.vim/autoload"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ "vim" ]

- name: create ~/.vim/colors diretory
  file:
    path: "/home/{{ user.name }}/.vim/colors"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ "vim" ]

- name: Clone vim-plug from github
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user.name }}/.vim/autoload/plug.vim"
  tags: [ "vim" ]

- name: Clone colors from github
  get_url:
    url: https://raw.githubusercontent.com/kristijanhusak/vim-hybrid-material/master/colors/hybrid_material.vim
    dest: "/home/{{ user.name }}/.vim/colors/hybrid_material.vim"
  tags: [ "vim" ]

- name: Generate ~/.vimrc
  template:
    src: vimrc.j2
    dest: "/home/{{ user.name }}/.vimrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
  notify: install plugins
  tags: [ "vim" ]
