---
- name: Install albert
  yay:
    name: albert
    user: "{{ user.name }}"
    dir: "/opt/"
  tags: ['albert']

- name: create ~/.config/albert diretory
  file:
    path: "/home/{{ user.name }}/.config/albert"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ 'albert' ]

- name: create ~/.config/autostart diretory
  file:
    path: "/home/{{ user.name }}/.config/autostart"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ 'albert' ]

- name: Copy config
  copy:
    src: files/albert.conf
    dest: "/home/{{ user.name }}/.config/albert/albert.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  tags: [ 'albert' ]

- name: Copy service file
  copy:
    src: files/albert.desktop
    dest: "/home/{{ user.name }}/.config/autostart/albert.desktop"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  tags: [ 'albert' ]

