---
# Bluetooth
- name: Install bluetooth
  yay:
    name: "{{ item }}"
    user: "{{ user.name }}"
    dir: "/opt/"
  with_items:
    - pulseaudio-alsa
    - bluez-utils
    - pulseaudio-modules-bt
    - libldac
  tags: [ 'sound' ]

- name: ensure ~/.config/systemd/user is dir
  file:
    path: "/home/{{ user.name }}/.config/systemd/user"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ 'sound' ]

- name: Copy config
  copy:
    src: files/mpris-proxy.service
    dest: "/home/{{ user.name }}/.config/systemd/user/mpris-proxy.service"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  tags: [ 'sound' ]

- name: configure pulseaudio
  blockinfile:
    block: |
      load-module module-switch-on-connect
      load-module module-bluetooth-discover a2dp_config="ldac_eqmid=hq ldac_fmt=f32"
      load-module module-echo-cancel use_master_format=1 aec_method=webrtc aec_args="analog_gain_control=0\ digital_gain_control=1" source_name=echoCancel_source sink_name=echoCancel_sink
      set-default-source echoCancel_source
      set-default-sink echoCancel_sink
    dest: /etc/pulse/default.pa
    state: present
  tags: [ 'sound' ]

- name: configure pulseaudio
  lineinfile:
    line: "AutoEnable=true"
    dest: /etc/bluetooth/main.conf
    state: present
  tags: [ 'sound' ]

- name: start bluetooth daemon
  systemd:
    name: bluetooth.service
    state: started
    daemon_reload: yes
    enabled: yes
  tags: [ 'sound' ]
