---
- name: Install Syncthing
  community.general.pacman:
    name: syncthing
    state: present
    update_cache: yes
  tags: ["syncthing"]

- name: Enable and start Syncthing service for user
  ansible.builtin.systemd:
    name: "syncthing@{{ ansible_user_id }}.service"
    enabled: yes
    state: started
  become: no
  tags: ["syncthing"]