---
- name: install tmux and dependencies
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  with_items:
    - tmux
    - tmuxinator
  tags: ['tmux']

- name: create ~/.config diretory
  file:
    path: "/home/{{ user.name }}/.config/"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ "tmux" ]

- name: create ~/.config/tmuxinator diretory
  file:
    path: "/home/{{ user.name }}/.config/tmuxinator/"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ "tmux" ]

- name: Copy config
  copy:
    src: files/work.yaml
    dest: "/home/{{ user.name }}/.config/tmuxinator/work.yaml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  tags: [ 'tmux' ]

- name: Copy config
  copy:
    src: files/home.yaml
    dest: "/home/{{ user.name }}/.config/tmuxinator/home.yaml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  tags: [ 'tmux' ]

- name: Copy config
  copy:
    src: files/.tmux.conf
    dest: "/home/{{ user.name }}/.tmux.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  tags: [ 'tmux' ]
